baseURL = "https://phisco.dev/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "hugo-theme-nix"
title = "Philippe Scorsolini"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  Name = "Philippe Scorsolini"
  HeaderUsername = "phisco"
  HeaderHostname = "localhost"
  About = "DevOps Engineer @ SIGHUP"
  ProfilePicture = "/img/avatar.jpg"
  GithubID = "phisco"
  Email = "p.scorsolini@gmail.com"
  LinkedInID = "phiscor"
  TwitterID = "Phisc0"
[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
